# fly.toml app configuration file generated for itsaydrian-stream on 2023-06-16T14:09:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itsaydrian-stream"
primary_region = "ewr"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
